import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import logo from '@img/logo.png'
import LoginPage from './LoginPage';
import axios from 'axios';
import React from 'react'
import { useEffect, useState } from 'react';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
//   const [onOffStatus, setOnOffStatus] = useState(null);

//   useEffect(() => {
//     fetchOnOffStatus();
//   }, []);

//   const fetchOnOffStatus = async () => {
//     try {
//       const response = await axios.get('/api/ambicam', {
//         params: { langflag: 'en' },
//       });

//       const { onOffStatus } = response.data;
//       setOnOffStatus(onOffStatus);
    
//   } catch (error) {
//     console.error('Error:', error);
//   }
// };
React.useEffect(() => {
  // Add an event listener to the contextmenu event to disable right-clicking
  document.addEventListener('contextmenu', handleContextMenu);

  // Cleanup the event listener when the component unmounts
  return () => {
    document.removeEventListener('contextmenu', handleContextMenu);
  };
}, []);
function handleContextMenu(e) {
  e.preventDefault();
}
  return (
    <>
      <Head>
        <title>Ambicam VMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
<script>

</script>
      </Head>
     
      <LoginPage />
 
      {/* <div>
      <h1>On/Off Status: {onOffStatus}</h1>
    </div> */}
    </>
  )
}
